version: 2

models:
  - name: stg_log
    description: "Raw ingested logs from local JSON batch pipeline."
    tests:
      - dbt_utils.expression_is_true:
          name: check_top_similarity_score_valid_range
          expression: "(top_similarity_score >= similarity_threshold AND top_similarity_score <= 1.0) OR (chunks_retrieved = 0 AND top_similarity_score = 0.0)"
          config:
            severity: warn
    columns:
      - name: query_id
        description: "Primary identifier for query logs"
        tests:
          - not_null
          - unique
      - name: session_id
        description: "Identifier for the user session"
        tests:
          - not_null
      - name: conversation_id
        description: "Identifier for the conversation thread"
        tests:
          - not_null
      - name: conversation_name
        description: "Name of the conversation thread"
        tests:
          - not_null
      - name: client_ip
        description: "IP address of the client making the query"
        tests:
          - not_null

      - name: user_query
        description: "The query string submitted by the user"
        tests:
          - not_null

      - name: selected_subject
        description: "The subject selected by the user for the query"
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['Tất cả', 'All', 'History', 'Literature', 'Geography']

      - name: selected_lesson
        description: "The lesson selected by the user for the query"
        tests:
          - not_null

      - name: similarity_threshold
        description: "The similarity threshold set for the query"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              arguments:
                expression: ">= 0 and similarity_threshold <= 1"

      - name: chunks_retrieved
        description: "Number of chunks retrieved for the query"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              arguments:
                expression: ">= 0"

      - name: top_similarity_score
        description: "The highest similarity score among the retrieved chunks"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              arguments:
                expression: ">= 0 and top_similarity_score <= 1"
      - name: ai_response
        description: "The response generated by the AI for the query"
        tests:
          - not_null

      - name: latency_seconds
        description: "Time taken to process the query in seconds"
        tests:
          - not_null

      - name: created_at
        description: "Timestamp when the query log was created"
        tests:
          - not_null